const mongoose = require('mongoose');

const WatchSessionSchema = new mongoose.Schema({
    user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
    },
    video: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Video',
        required: true,
    },
    // The unique ID for this specific session, generated by the client or server
    sessionId: {
        type: String,
        required: true,
        unique: true,
    },
    // The last reported timestamp from the player (e.g., 120.5 seconds)
    lastReportedTime: {
        type: Number,
        default: 0,
    },
    // To prevent abuse, we'll stop heartbeats after 10s of inactivity
    lastHeartbeatAt: {
        type: Date,
        default: Date.now,
    },
    status: {
        type: String,
        enum: ['active', 'ended'],
        default: 'active',
    },
}, { timestamps: true });

// Index for quickly finding a user's active sessions
WatchSessionSchema.index({ user: 1, video: 1, status: 1 });

module.exports = mongoose.model('WatchSession', WatchSessionSchema);